CREATE TABLE users(
  userID INTEGER PRIMARY KEY AUTOINCREMENT,
  fullname VARCHAR(40) NOT NULL,
  email VARCHAR(40) NOT NULL,
  pword VARCHAR(256) NOT NULL,
  phone VARCHAR(256) NOT NULL,
  picture VARCHAR(200),
  tagID INTEGER,
  FOREIGN KEY(tagID) REFERENCES tags ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE tags(
  tagID INTEGER NOT NULL,
  outdoor_adventures BOOLEAN NOT NULL,
  cooking BOOLEAN NOT NULL,
  gaming BOOLEAN NOT NULL,
  night_life BOOLEAN NOT NULL,
  swimming BOOLEAN NOT NULL,
  weight_lifting BOOLEAN NOT NULL,
  photography BOOLEAN NOT NULL,
  yoga BOOLEAN NOT NULL,
  basketball BOOLEAN NOT NULL,
  dancing BOOLEAN NOT NULL,
  PRIMARY KEY(tagID)
);

CREATE TABLE events(
  eventID INTEGER NOT NULL,
  eventName VARCHAR(100) NOT NULL,
  eventDescription VARCHAR(200) NOT NULL,
  host VARCHAR(40) NOT NULL,
  phone VARCHAR(256) NOT NULL,
  picture VARCHAR(200),
  tagID INTEGER,
  PRIMARY KEY(eventID),
  FOREIGN KEY(tagID) REFERENCES tags ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE userEventInfo(
  userID INTEGER NOT NULL,
  eventID INTEGER NOT NULL,
  commitStatus INTEGER NOT NULL,
  PRIMARY KEY(userID, eventID),
  FOREIGN KEY(userID) REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(eventID) REFERENCES events ON DELETE CASCADE ON UPDATE CASCADE
  CONSTRAINT Chck_Status CHECK (commitStatus IN (0, 1))
);